source 'https://rubygems.org'
gem 'sinatra'
gem 'sqlite3'
gem 'rest-client', '< 1.8'
gem 'wunderlist-api', :git => 'https://github.com/codeZeilen/wunderlist-api.git', :branch => 'completed-at-and-user-interface'
gem 'unicorn'
